apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp-container
          image: shestera/scaletestapp:latest
          resources:
            limits:
              memory: "30Mi"
          ports:
            - containerPort: 8080