type Client {
    id: ID!
    name: String
    age: Int
    documents: [Document]
    relatives: [Relative]
}

type Document {
    id: ID!
    type: String
    number: String
    issueDate: String
    expiryDate: String
}

type Relative {
    id: ID!
    relationType: String
    name: String
    age: Int
}

type Query {
    client(id: ID!): Client
}

query GetClient($id: ID!) {
    client(id: $id) {
        id
        name
        age
    }
}

query GetClientDocuments($id: ID!) {
    client(id: $id) {
        documents {
            id
            type
            number
            issueDate
            expiryDate
        }
    }
}

query GetClientRelatives($id: ID!) {
    client(id: $id) {
        relatives {
            id
            relationType
            name
            age
        }
    }
}

query GetFullClientInfo($id: ID!) {
    client(id: $id) {
        id
        name
        age
        documents {
            id
            type
            number
            issueDate
            expiryDate
        }
        relatives {
            id
            relationType
            name
            age
        }
    }
}

query GetClientWithDocuments($id: ID!) {
    client(id: $id) {
        id
        name
        age
        documents {
            id
            type
            number
            issueDate
            expiryDate
        }
    }
}

query GetClientWithRelatives($id: ID!) {
    client(id: $id) {
        id
        name
        age
        relatives {
            id
            relationType
            name
            age
        }
    }
}

query GetClientDocumentsAndRelatives($id: ID!) {
    client(id: $id) {
        documents {
            id
            type
            number
            issueDate
            expiryDate
        }
        relatives {
            id
            relationType
            name
            age
        }
    }
}